- plugins/modulbank/ZenmoneyManifest.xml
- plugins/modulbank/main.js
- plugins/modulbank/preferences.xml
Get accounts
Get transactions
Merge transfer acros personal accounts transactions
> modulbank.ru plugin base functionality

- plugins/belswissbank/main.js
> [belswissbank] bugfixes

- plugins/belswissbank/main.js
- plugins/belswissbank/preferences.xml
- plugins/belswissbank/utils.js
При тестировании на реальном девайсе оказалось, что Android app падает. Возникло предположение, что CheckBoxPreference не заимплеменчен. Заменил на строковый инпут.
> [belswissbank] use logging categories string instead of checkbox

- plugins/chelinvest/ZenmoneyManifest.xml
- plugins/chelinvest/main.js
Предыдущая версия плагина получала от сервера 500 ошибку. Т.к. в debugger'е всё и так работало, предполагаю, что не хватает заголовков. Добавил все заголовки, которые передаются хромом.
> [chelinvest] Добавил заголовки к запросам

- plugins/modulbank/main.js
synkID refctor to 4 chars format
active accounts checking fix
> [modulbank] bugfix

- plugins/modulbank/main.js
Check sms code
Check token
Tracing process points
> [modulebank] refactor

- plugins/rocketbank/main.js
[ZP]: Exception: TypeError: undefined is not an object (evaluating 'this.deposits_percent.push')
[ZP]: Call stack:
forEach@[native code]
forEach@[native code]
fetchDeposits
sync
main
global code
> [rocketbank] fix exception

- plugins/chelinvest/ZenmoneyManifest.xml
- plugins/chelinvest/main.js
Добавил обработку операций с наличными.
Обсуждение [тут](https://github.com/zenmoney/ZenPlugins/pull/41#issuecomment-284653322)
> [chelinvest] Fix: Cash transactions

- plugins/raiffeisen/main.js
Добавила обработку неожиданных ответов сервера для всех используемых сервисов.
> [raiffeisen] log improvements

- plugins/raiffeisen/main.js
Убрала импорт карт, теперь при обработке карт составляю мапу из номера счёта и номеров карт, привязанных к этому счёту. При обработке счетов проверяю, привязаны ли к нему карты: если нет, то это "checking"; иначе импортирую его как "ccard" с номером первой привязанной к нему карты (todo: при выборе номера игнорировать допкарты).
Поменяла titles импортируемым кредитам и вкладам.
Починила импорт процентов по вкладам и упростила логику для вычисления endDateOffset.
> [raiffeisen] Фиксы для импорта операций по картам и импорта вкладов

- plugins/chelinvest/ZenmoneyManifest.xml
- plugins/chelinvest/main.js
- plugins/chelinvest/preferences.xml
Исправил ошибки, добавил функционал.
> Chelinvest/bump version 1.1

- plugins/belswissbank/BSB.js
- plugins/belswissbank/preferences.xml
- plugins/belswissbank/utils.js
this flexibility is required to provide test data for mobile app debugging
> [belswissbank] add apiUrl preference for debugging purposes

- plugins/raiffeisen/main.js
Убрала проверку на адекватность ответа от сервера при авторизации
Добавлен вывод в лог даты открытия вклада (для определения формата) и установка сегодняшней даты, если не сможем распарсить openDate
> [raiffeisen] Логирование для авторизации и импорта вкладов

- plugins/raiffeisen/main.js
Это дубликаты реальных транзакций для кредитных карт, они добавляются в день реального проведения денег и записываются с отрицательным знаком: для расходов это будет операция пополнения, для доходов, наоборот, операция снятия.
> [raiffeisen] Сделала пропуск операций с пометкой "CREDIT CARD POSTING"

- plugins/kykyryza/ZenmoneyManifest.xml
- plugins/kykyryza/classes/BankKykyryza.js
В логируемых данных не оказалось кредитного лимита
Пробуем логировать данные всего счета
> [kykyryza] log account data

- plugins/beeline/ZenmoneyManifest.xml
- plugins/beeline/classes/Request.js
http://support.zenmoney.ru/topics/279-bank-bilajn-poklyuchenie-multikartochnogo-scheta-undefined-is-not-an-object/
> Beeline fixes

- plugins/beeline/ZenmoneyManifest.xml
- plugins/beeline/classes/BankBeeline.js
Для http://support.zenmoney.ru/topics/282-kreditnyij-limit-pri-nastrojke-podklyucheniya-banka-bilajn/
> Beeline log account data

- plugins/epayments/classes/Request.js
Добавил поддержку OTP в ePayments, также изменил немного код для авторизации, чтобы он определял тип ошибки по ее имени а не описании. Так как для OTP возможно выбрать только Google Authenticator, то и регулярка кодов сгенерированным им - 6 цифр
> [epayments] OTP support added; More error checks added

- plugins/epayments/classes/Request.js
Немного изменил стиль кода, переименовал переменные, например вместо requestData - response, потому что это ответ сервера а не данные для запроса. Вынес headers в const, разделил функцию авторизации чтобы можно было вызывать рекурсивно если есть потребность ввести OTP. И самое главное - заменил GET у тестовой страницы на HEAD это должно ускорить подключение секунд на 15 (во всяком случае у меня так). Согласно wiki - HEAD этот тот же GET только без тела, то есть HEAD и GET возвращают один и тот же статус код, а нам это главное.
> [epayments] Рефакторинг, оптимизация

- src/plugins/raiffeisen/index.js
15-го посмотрю, как происходит платёж по кредиту -- возможно, добавлю что-нибудь.
> [raiffeisen] added loan processing

- plugins/openbank/main.js
> [openbank] Даты в формате timestamp

- plugins/openbank/ZenmoneyManifest.xml
- plugins/openbank/main.js
> [openbank] Корректировка часового пояса

- plugins/openbank/ZenmoneyManifest.xml
- plugins/openbank/main.js
> [openbank] Правильная корректировка времени

- plugins/openbank/ZenmoneyManifest.xml
- plugins/openbank/main.js
> [openbank] Кнопка для лога на время теста

- plugins/openbank/ZenmoneyManifest.xml
- plugins/openbank/main.js
> [openbank] Установка cookie через ZenMoney.setCookie

- plugins/openbank/ZenmoneyManifest.xml
- plugins/openbank/main.js
#160 
Обнуление куки делается только если до этого куки задавали.
> [openbank] Исправлено обнуление cookie access_token

- plugins/openbank/ZenmoneyManifest.xml
- plugins/openbank/main.js
> [openbank] Переделано распознавание переводов между своими счетами

- plugins/openbank/ZenmoneyManifest.xml
- plugins/openbank/main.js
> [openbank] Исправлена коррекция времени транзакции

- plugins/openbank/ZenmoneyManifest.xml
- plugins/openbank/main.js
> Фиксы по Открытию

- .idea/inspectionProfiles/Project_Default.xml
- src/plugins/alfabank/api.js
- src/plugins/alfabank/converters.js
- src/plugins/alfabank/converters.test.js
- src/plugins/alfabank/index.js
guessing by amountDebt is not correct because amountDebt >= 0 hides own funds
> [alfabank] get creditLimit info from api

- src/plugins/alfabank/converters.js
(not loan with rates, payment intervals etc. yet)
> [alfabank] map non-card credit account to {startBalance, balance}

- src/plugins/alfabank/converters.js
(fallback on guessing or throw detailed error)
> [alfabank] expect both movement receiver/sender can be missing 

- src/plugins/priorbank/converters.js
it satisfies fresh known resultsets uniqueness (but still is not perfect due to missing time on non-holds)
> [priorbank] choose accounted amount for transfer natural transaction id

- plugins/modulbank/main.js
- plugins/modulbank/preferences.xml
Я переписал модуль синхронизации с Модульбанком, вместо логина с паролем используется токен API, который каждый пользователь может сгенерировать в Личном кабинете.
В браузере вроде работает, загружает счета и транзакции. Первый раз все, затем только новые.
**TODO:**
Очень хотел бы протестировать в живом приложении. Что для этого нужно сделать?
> Синхронизация с Модульбанком

- plugins/openbank/ZenmoneyManifest.xml
Set **codeRequired** attribute to **false**, so the plugin will be able to sync automatically.
> [openbank] set codeRequired = false

- .gitignore
- .idea/codeStyles/Project.xml
- .idea/vcs.xml
- src/consoleAdapter.js
- src/plugins/alfabank/converters.js
affected 10+ accounts
caused by fuzzy transfer merge criterion — we're improving isTransfer predicate while still stuff like deposits gets matched as transfers
> [alfabank] fix "ambiguous values" issues

- src/plugins/bgpb/api.js
- src/plugins/bgpb/index.js
- src/plugins/mtbank/__tests__/converters/transactions/transactions.test.js
- src/plugins/mtbank/converters.js
- src/plugins/mtbank/index.js
BGPB обновлять не нужно, эта версия уже на продакшене. Нужно обновить только МТБанк
> [mtbank] [bgpb] Skip frozen operations.

- src/plugins/mtbank/__tests__/converters/transactions/cash.test.js
- src/plugins/mtbank/converters.js
Правильная обработка снятия налочных в банкоматах других банков
> [mtbank] Cash withdraw transaction in other banks

- src/plugins/alfabank-by/__tests__/converters/transactions.test.js
- src/plugins/alfabank-by/api.js
- src/plugins/alfabank-by/converters.js
- src/plugins/alfabank-by/index.js
Добавлена правильная обработка ЕРИП транзакций + обработаны запросы на конвертацию валют с предложенным клиентом курсом обмена.
Спрятаны для логов некоторые данные.
> [alfabank-by] Process ERIP transactions and skip currency order transactions

- src/plugins/bgpb/__tests__/converters/transactions.test.js
- src/plugins/bgpb/converters.js
Обработка снятия наличных в банкоматах. В этой доработке добавляется еще одна операция пополнения на cash счет
> [bgpb] ATM Cash withdrawal processing

- src/plugins/bnbank/__tests__/converters/transactions/transaction.test.js
- src/plugins/bnbank/converters.js
Обработка капитализации депозитов.
> [bnbank] Deposit capitalization processing

- src/plugins/alfabank-by/__tests__/index.test.js
- src/plugins/alfabank-by/api.js
- src/plugins/alfabank-by/converters.js
- src/plugins/alfabank-by/index.js
Здесь добавлен фикс ошибки, когда знаки при конввертации валют могли различаться.
+ добавлен вызов данных о депозитах и кредитах для сбора логов. Депозиты и кредиты пока не интегрированы, но это один из этапов их интеграции.
> Alfabank by 05 14 dep and cred

- src/plugins/alfabank-by/__tests__/converters/transactions.test.js
- src/plugins/alfabank-by/__tests__/index.test.js
- src/plugins/alfabank-by/api.js
- src/plugins/alfabank-by/converters.js
- src/plugins/alfabank-by/index.js
В обновлении:
- Правильная обработка локации произведения транзакции
- Убираем лишние и бессмысленные комментарии
- Игнорирование транзакций с нулесыми списаниями, которые приводили к ошибкам синхронизации
- Сибираем больше информации о кредитах и депозитах (пока только в для разработчиков)
> [alfabank-by] Process locations and comments for transactions.

- src/plugins/belinvestbank/__tests__/index.test.js
- src/plugins/belinvestbank/converters.js
- src/plugins/bgpb/api.js
- src/plugins/bgpb/converters.js
Обработка больших балансов на карточке
> [belinvestbank] Process big numbers in balance

- src/plugins/alfabank-by/__tests__/converters/accounts.test.js
- src/plugins/alfabank-by/__tests__/index.test.js
- src/plugins/alfabank-by/converters.js
- src/plugins/alfabank-by/index.js
Добавлена синхронизация депозитов
> [alfabank-by] Deposit processing

- src/plugins/mtbank/__tests__/converters/accounts.test.js
- src/plugins/mtbank/__tests__/converters/transactions/transactions.test.js
- src/plugins/mtbank/__tests__/index.test.js
- src/plugins/mtbank/api.js
- src/plugins/mtbank/converters.js
Интегрирована новая версия API.
Полагаю что будет много багов, ибо API сильно поменяли, поэтому нужно будет фиксить уже по обращениям
> [mtbank] Implement new api

- src/plugins/bnbank/api.js
Обработка случая, когда в списке операцих xml выгрузки только одна транзакция, которая ранее приводила к ошибке.
> [bnbank] Fix xml processing of just one operation

- src/plugins/mtbank/api.js
У банка обновилось API и текущая версия не работает.
Это фикс
> [mtbank] Fix to new API

- src/plugins/mtbank/__tests__/converters/transactions/cash.test.js
- src/plugins/mtbank/converters.js
Обработка пооплнений карточек через инфокиоск.
> [mtbank] Process inserting from cash to card in info-kiosk

- src/plugins/alfabank-by/index.js
Текущий ПР убирает транзакции оплаты кредитов, чтоб не возникала корректировка на кредитном счете.
> [alfabank-by] Fix credit transfer transactions

- src/plugins/belarusbank/ZenmoneyManifest.xml
- src/plugins/belarusbank/__tests__/converters/accounts.test.js
- src/plugins/belarusbank/__tests__/converters/transactions/cash.test.js
- src/plugins/belarusbank/__tests__/converters/transactions/transction.test.js
- src/plugins/belarusbank/api.js
- src/plugins/belarusbank/converters.js
- src/plugins/belarusbank/index.js
- src/plugins/belarusbank/preferences.xml
Данные забираются через веб интернент-банк. Т.к. парсится html, не все аккаунты заведутся сразу.
В связи с понятными сложностями, плагин не умеет выгружать все транзакции, что были в банке, но он выгрузит все последние операции по карточкам.
В плагине есть интеграция с депозитами, но пополнение и списание депозита удалось реализовать только через корректировку. Даже последние транзакции не депозитам не загружаются.
> Belarusbank integration

- src/plugins/belarusbank/api.js
- src/plugins/belarusbank/preferences.xml
Signed-off-by: Slava Shahoika <vistova@gmail.com>
> [belarusbank] Add ability to fill codes with plus and space

- src/plugins/mtbank/converters.js
Signed-off-by: Slava Shahoika <vistova@gmail.com>
> [mtbank] Skip zero transactions such as verification

- src/plugins/alfabank-by/__tests__/converters/transactions.test.js
- src/plugins/alfabank-by/converters.js
- src/plugins/alfabank-by/index.js
Исправлени:
https://github.com/zenmoney/ZenPlugins/issues/314
> [alfabank-by] Fix company transfer transactions

- src/plugins/belarusbank/__tests__/converters/transactions/cash.test.js
- src/plugins/belarusbank/__tests__/converters/transactions/transaction.test.js
- src/plugins/belarusbank/api.js
- src/plugins/belarusbank/converters.js
Исправление https://github.com/zenmoney/ZenPlugins/issues/344
> [belarusbank] Fix card balance and comment parsing

- src/plugins/alfabank/__tests__/__snapshots__/converters.test.js.snap
- src/plugins/alfabank/__tests__/converters.test.js
- src/plugins/alfabank/converters.js
> [alfabank] fixed description merchant parser

- src/plugins/alfabank-by/converters.js
> [alfabank-by] Fix syncID matcher.

- src/plugins/bnbank/api.js
Судя по всему БНБанк поменял свой API, за счет чего стал выдавать больше информации + ломать предыдущую логику
> [BNBank] Update cards api fetching

- src/plugins/alfabank-by/api.js
Обработка авторизации для нерезидентов РБ.
Обращаю внимание, что в плагин нельзя авторизироваться используя логин и пароль, т.к. плагин эмулирует работу inSync.by приложения, в котором такой возможности нет. Вам нужно вводить номер паспорта точно так-же, как Вы вводите в приложение.
> [alfabank-by] Handle no-resident passports

- src/plugins/belinvestbank/converters.js
Белинвестбанк не отдает информацию про дочерние карточки. Поэтому здесь делалась обработка случаев, когда идет списание с таких карточек + обработка пополнений на такого типа карточки.
> [Belinvestbank] Process child credit cards

- src/plugins/alfabank-by/api.js
Signed-off-by: Slava Shahoika <vistova@gmail.com>
> [alfabank-by] Show password message form bank

- src/plugins/alfabank-by/__tests__/converters/accounts.test.js
- src/plugins/alfabank-by/__tests__/converters/transactions.test.js
- src/plugins/alfabank-by/converters.js
- src/plugins/alfabank-by/index.js
Объединение дополнительной с родительской карточкой, если такие есть в аккаунте
> Alfabank child card merging

- src/plugins/alfabank-by/converters.js
- src/plugins/alfabank-by/index.js
У меня есть подозрение что это должно помочь излечить плагин от постоянных корректировок транзакиций
> [Alfabank-by] Add transactions sort by date

- src/plugins/psbank/__tests__/converters/transactions.test.js
- src/plugins/psbank/api.js
- src/plugins/psbank/converters.js
- src/plugins/psbank/index.js
1. Кредиты выгружаются как счета.
2. Операции на обычных счетах в сторону кредита помечаются как переводы.
> [Psbank] Работа с кредитами

- src/plugins/belarusbank/api.js
> [belarusbank] Change transactions regexp for API

- src/plugins/bgpb/__tests__/converters/transactions.test.js
- src/plugins/bgpb/api.js
- src/plugins/bgpb/converters.js
Обратите внимание, после этого изменения балансы овердрафтных счетов поменяются и возникнут корректировки.
Банк возвращает в балансе доступную для использования сумму, ZenMoney работает именно с реальным балансом
> [bgpb] Fix overdraft and Money movement processing

- src/plugins/sovest/converters.js
- src/plugins/sovest/converters.test.js
Неверно рассчитывался текущий баланс. Отображало доступные средства, сейчас отображается отрицательный баланс, равный сумме задолженности от лимита
> [sovest] Fix balance count minus

- src/plugins/bnbank/__tests__/index.test.js
- src/plugins/bnbank/api.js
- src/plugins/bnbank/converters.js
- src/plugins/bnbank/index.js
Здесь исправлены частые ошибки что были в плагине:
- корректировки
- двойные транзакции
Добавлена поддержка новой версии API
> [bnbank] Implement new API

- src/plugins/epayments/ZenmoneyManifest.xml
- src/plugins/epayments/__tests__/api/auth.test.js
- src/plugins/epayments/__tests__/api/transactions.test.js
- src/plugins/epayments/api.js
- src/plugins/epayments/auth.js
- src/plugins/epayments/converters.js
- src/plugins/epayments/index.js
-  Переработан модуль авторизации
- Добавленна поддержка Strong Customer Authenticator
- Улучшена обработка ошибок
- access и refresh токены теперь записываются в хранилище, позволяя иногда обойтись без повторной авторизации (срок жизни refresh токена, похоже, несколько часов)
- Использован API транзакций v3 (появились новые поля, пока никак не используются плагином)
> Обновление для ePayments

- src/plugins/solutionbank/ZenmoneyManifest.xml
- src/plugins/solutionbank/__tests__/converters/accounts.test.js
- src/plugins/solutionbank/__tests__/converters/transactions/transactions.test.js
- src/plugins/solutionbank/api.js
- src/plugins/solutionbank/converters.js
- src/plugins/solutionbank/index.js
- src/plugins/solutionbank/preferences.xml
Интеграция для Банка Решение в Беларуси. Проинтегрирована работа только с карточками. Если нужно будет больше интеграций, то нужны аккаунты-доноры, т.к. я интегрировал этот банк чисто по фану.
Обратите внимание, что из-за нюнсов работы банка, чаще всего транзакции будут работать через корректировку. Связано это с тем, что в банке отображаются транзакции только после проведения. Старые транзакции подгрузятся нормально, т.к. они будут выгружаться через "Выписка" в мобильном приложении.
В мобильном банкинге есть возможность смотреть транзакции сразу в "Мини выписка", однако эта услуга на сегодняшний день стоит 1 рубль за одну выписку. Мини выписка бесплатна для всех виртуальных карт, либо карт в EUR и USD. Поэтому для таких карт плагин делает запрос минивыписка при каждой синхронизации, чтоб …
> [solutionbank] Initial commit

- src/plugins/click-uz/ZenmoneyManifest.xml
- src/plugins/click-uz/api.js
- src/plugins/click-uz/converters.js
- src/plugins/click-uz/index.js
- src/plugins/click-uz/preferences.xml
TODO на будущее:
- Проверить работу плагина с аккаунтом, к которому добавлены фирменные карты Click от Agrobank и Asia Alliance Bank
- Проверить выписку при пополнении кошелька картами Visa/MasterCard/МИР, чтобы реализовать `invoice` в модели транзакции
- Проверить выписку при переводах между картами и кошельком, чтобы реализовать правильные `movements` в модели транзакции
- Проверить работу плагина с картами Humo
Сам я не собираюсь реализовывать вышеописанные кейсы, по крайней мере в ближайшем будущем, т.к. собираюсь использовать плагин только с подтягиванием кошелька, т.к. при оплате им начисляются 2% кэшбека.
Дисклеймер: данный плагин интеграции был сделан в нерабочие выходные дни и в свободное от основной моей работы время. Данный плагин интеграции сделан в первую очередь для моего …
> First work version of click-uz integration plugin

- src/plugins/ineco/converters.js
- src/plugins/ineco/index.js
почему-то на устройстве транзакции не добавляются, хотя локально все работает
> [ineco] add debug info

- src/plugins/ineco/converters.js
- src/plugins/ineco/helpers.js
- src/plugins/ineco/index.js
- src/plugins/ineco/session.js
из-за того, что файлы на мобильном устройстве приходят с непонятными пустыми символами, пробуем получать их как бинарный буфер
> [ineco] get file as binary data

- src/plugins/comdirect/ZenmoneyManifest.xml
- src/plugins/comdirect/__tests__/converters/accounts.test.js
- src/plugins/comdirect/__tests__/converters/transactions.test.js
- src/plugins/comdirect/bank.js
- src/plugins/comdirect/converters.js
- src/plugins/comdirect/index.js
- src/plugins/comdirect/preferences.xml
Написал плагин для немецкого банка comdirect.
> [comdirect] Новый плагин для comdirect bank (Германия)

- src/plugins/comdirect/__tests__/converters/transactions.test.js
- src/plugins/comdirect/bank.js
- src/plugins/comdirect/converters.js
Поправил ошибку, которое выдавало приложение – дата транзакции была строкой вместо Date-объекта (при отладке в песочнице не ругалось).
Мелкие улучшения для смены типа подтверждения TAN.
> [comdirect] conversion fix for date format, auth type switching improvements

- src/plugins/rrbbank/converters.js
> fix the case: all merchant properties are null

- src/plugins/dabrabyt/ZenmoneyManifest.xml
- src/plugins/dabrabyt/api.js
- src/plugins/dabrabyt/converters.js
- src/plugins/dabrabyt/index.js
- src/plugins/dabrabyt/preferences.xml
Тесты писать обязательно? какие части должны быть покрыты?
> Плагин синхронизации с банком "Дабрабыт"

- src/plugins/ineco/helpers.js
- src/plugins/ineco/index.js
- src/plugins/ineco/session.js
> Ineco sms auth

- src/plugins/dabrabyt/index.js
Desc of fix: checked nullability of account(if not confirmed - it is going to be null)
> Dabrabyt: sync error when there is one or more unconfirmed cards

- package.json
- src/plugins/dabrabyt/index.js
- src/plugins/statusbank/ZenmoneyManifest.xml
- src/plugins/statusbank/__tests__/api.test.js
- src/plugins/statusbank/__tests__/converters/accounts.test.js
- src/plugins/statusbank/__tests__/converters/transactions.test.js
- src/plugins/statusbank/api.js
- src/plugins/statusbank/converters.js
- src/plugins/statusbank/index.js
- src/plugins/statusbank/preferences.xml
The first version of statusbank
Problem from StatusBank:
every sync it will send you SMS(also as ibank) - we can't fix it before statusbank wouldn't fix it
Problem from StatusBank:
Deposit operations can be scratched only for the last month.
What this integration cannot do:
1. Deposits/overdrafts
2. (Not tested) sending money from card to card
> Statusbank implementation v 0.1

- src/plugins/forwardbank/ZenmoneyManifest.xml
- src/plugins/forwardbank/__tests__/converters/accounts/card.test.js
- src/plugins/forwardbank/__tests__/converters/transactions/income.general.test.js
- src/plugins/forwardbank/__tests__/converters/transactions/income.internal.test.js
- src/plugins/forwardbank/__tests__/converters/transactions/outcome.external.test.js
- src/plugins/forwardbank/__tests__/converters/transactions/outcome.general.test.js
- src/plugins/forwardbank/api.js
- src/plugins/forwardbank/converters.js
- src/plugins/forwardbank/index.js
- src/plugins/forwardbank/preferences.xml
Плагин синхронизации с банком Форвард Банк (Украина)
> Add forwardbank plugin

- src/plugins/bnbank/api.js
BNB requires to bump version.
Just a small code edit :)
> [bnbank] Bump version

- src/plugins/statusbank/api.js
- src/plugins/statusbank/index.js
Added recalculation system for date periods(Status bank is showing reports for "the last work day" - but sometimes - not last - e.x. for the first days of the month.
Also fixed some null errors.
Added fixes for some issues like "Нет данных для отчета"
> [statusbank] Work with edge-cases, fix some issues

- src/plugins/forwardbank/__tests__/converters/accounts/card.test.js
- src/plugins/forwardbank/__tests__/converters/transactions/income.general.test.js
- src/plugins/forwardbank/__tests__/converters/transactions/income.internal.test.js
- src/plugins/forwardbank/__tests__/converters/transactions/outcome.external.test.js
- src/plugins/forwardbank/__tests__/converters/transactions/outcome.general.test.js
- src/plugins/forwardbank/api.js
- src/plugins/forwardbank/converters.js
- Фикс общей суммы на счету с учетом кредитного лимита
- Убрал лишние данные в комментарии к транзакции
> [forwardbank] Fix available balance, clean up transaction comment

- src/plugins/westernbid/ZenmoneyManifest.xml
- src/plugins/westernbid/index.ts
- src/plugins/westernbid/preferences.xml
Аккаунт в этой системе может быть только один и только в долларах, поэтому account id & syncIds hardcoded
[Ссылка на Swagger WesternBid](https://www.westernbid.info/swagger/ui/index#/BalanceController)
> WesternBid plugin

- src/plugins/kapitalbank-uz/api.js
- src/plugins/kapitalbank-uz/index.js
- src/plugins/kapitalbank-uz/preferences.xml
С текущей версией плагина никак не удавалось авторизоваться.
В итоге, поковыряв мобильное приложение, выяснил, что аутентификационная последовательность изменилась. Также стал ненужным параметр "мобильный телефон" (приложение при авторизации тоже его не запрашивает).
> [kapitalbank-uz] fix login sequence

- src/plugins/kapitalbank-az/ZenmoneyManifest.xml
- src/plugins/kapitalbank-az/api.js
- src/plugins/kapitalbank-az/converters.js
- src/plugins/kapitalbank-az/index.js
- src/plugins/kapitalbank-az/preferences.xml
> [kapitalbank-az] first commit

- src/plugins/statusbank/api.js
AR:
Statusbank crashes because of 2 errors, connected with not filtering headers and '\n' data
ER:
Statusbank is working great by getting only tbody and td data
> [statusbank] fix: crashes on Deposits

- src/plugins/ininal/ZenmoneyManifest.xml
- src/plugins/ininal/api.ts
- src/plugins/ininal/converters.ts
- src/plugins/ininal/index.ts
- src/plugins/ininal/models.ts
- src/plugins/ininal/preferences.xml
Плагин для Турецкого электронного кошелька ininal.
> [ininal] new plugin for ininal.com

- src/plugins/tronscan/ZenmoneyManifest.xml
- src/plugins/tronscan/api.ts
- src/plugins/tronscan/config.ts
- src/plugins/tronscan/converters.ts
- src/plugins/tronscan/index.ts
- src/plugins/tronscan/preferences.xml
Добавлена возможность подключить кошелек в сети Tron и [отслеживать](https://tronscan.org/#/address/TAzsQ9Gx8eqFNFSKbeXrbi45CuVPHzA8wr/transfers) транзакции со стейблкоинами (USDT, TUSD, USDD, USDC)
> feat: add tronscan stablecoins

- src/plugins/tronscan/api.ts
Tron API has a limit of 3 requests per second. If the number of wallets is at least more than two, this leads to an error at the moment.
> fix tron rps

- src/plugins/apelsin-uz/api.js
- src/plugins/apelsin-uz/converters.js
- src/plugins/apelsin-uz/index.js
This should fix https://github.com/zenmoney/ZenPlugins/issues/708
> [apelsin-uz] Added transactions for Mastercard cards

- src/polyfills/crypto.js
Попытка починить ошибку can't find variable: atob (https://github.com/zenmoney/ZenPlugins/pull/712#issuecomment-1914522038)
> [Raiffeisen-RS] Add atob and btoa functions

- src/plugins/tinkoff-business/api.js
bank-accounts v2 is deprecated
bank-accounts v4 include:
1. added overnight accounts
2. added special accounts and business piggy bank accounts
3. in AccountInfo added fiels status, tariffName, tariffCode, createdOn, mainFlag balance.balance, balance.realOtb;
4. added investment accounts
> tinkoff-business api upd bank-accounts to v4

- src/plugins/postal-savings-rs/__tests__/converters/transactions/payment.test.ts
- src/plugins/postal-savings-rs/converters.ts
Для некоторых операций возвращалась ошибка, что title пустой.
@skvav подвёз hotfix.
> [Postal-Savings-RS] Fix empty title for some operations

- src/plugins/tbc-ge/api.ts
- src/plugins/tbc-ge/converters.ts
- src/plugins/tbc-ge/fetchApi.ts
- src/plugins/tbc-ge/legacy/fetchApi.ts
- src/plugins/tbc-ge/models.ts
Remove alert when need to enter another trust code
Handle UTIL_PAY category
Create a fallback transaction instead of throwing an error
> [tbc-ge] Alert, Utils and Fallback transaction

- src/plugins/raiffeisen-rs/__tests__/converters/transactions/topup.test.ts
- src/plugins/raiffeisen-rs/converters.ts
- src/plugins/raiffeisen-rs/fetchApi.ts
1.  Поправил падение при обработке транзакции с комиссией за SWIFT.
2. Распараллелил запросы на сервер.
3. Добавил транзакции с наличными.
> [Raiffeisen-RS] A few improvements

- src/plugins/tbc-ge/api.ts
- src/plugins/tbc-ge/converters.ts
- src/plugins/tbc-ge/fetchApi.ts
- src/plugins/tbc-ge/index.ts
- src/plugins/tbc-ge/legacy/index.ts
- src/plugins/tbc-ge/models.ts
- src/plugins/tbc-ge/utils.ts
Add deposits
Remove background checks
Handle 401
Change device id creation
Create OTP device priority
> [tbc-ge] Add deposits

- src/plugins/tbc-ge/api.ts
- src/plugins/tbc-ge/fetchApi.ts
- src/plugins/tbc-ge/models.ts
Fix auth loss
Add sanitizing to fetchLoginByPasswordV2
Add timeouts to OTP code sending
> [tbc-ge] Fix auth loss

- src/plugins/tbc-ge/api.ts
- src/plugins/tbc-ge/fetchApi.ts
Add another error handler for trusting already trusted device because the bank changed API
> [tbc-ge] Fix existing trusted device error

- src/plugins/tbc-ge/api.ts
- src/plugins/tbc-ge/fetchApi.ts
- src/plugins/tbc-ge/index.ts
Add new errors
Fix error in fetchUnTrustDeviceV2 if not trusted
> [tbc-ge] Fix untrusting device and add new errors

- src/plugins/tbc-ge/api.ts
- src/plugins/tbc-ge/fetchApi.ts
Assume that Vasco is TBC Pass
Specify sanitizing for fetchGetSessionIdV2
Remove check for multiple OTP devices
> [tbc-ge] Potential fix auth for TBC Pass

- src/plugins/postal-savings-rs/index.ts
> [postal-savings-rs] Filter account transactions by date

- src/plugins/belinvestbank/__tests__/index.test.js
- src/plugins/belinvestbank/api.js
Change version of plugin to actual, which is supported by bank's API.
> feat: update version to actual

- src/ZPAPI.js
- src/plugins/tbc-ge/api.ts
- src/plugins/tbc-ge/converters.ts
- src/plugins/tbc-ge/fetchApi.ts
- src/plugins/tbc-ge/index.ts
- src/plugins/tbc-ge/models.ts
- src/types/zenmoney.ts
Add support of loans for TBC bank Georgia.
> [tbc-ge] Add support for loans.

- src/plugins/tbc-ge/converters.ts
- src/plugins/tbc-ge/models.ts
Fix parsing of standard movement operation. Ignore unparsable title and set default values to not lose operations. Add cash in support with terminal. Update Util payment logic to support other util types apart with mobile.
> [tbc-ge] Fix parsing of standard movement operation. Add improvements.

- src/plugins/tbc-ge/__tests__/convertersV2/transactions/utilsTransactions.test.ts
- src/plugins/tbc-ge/common-tests/classes.ts
- src/plugins/tbc-ge/fetchApi.ts
- src/plugins/tbc-ge/models.ts
Fix error `[RUE] Assertion failed: sum should be a number, got NaN` in Utils transactions
Add tests for Utils transactions
Enable sanitizing of user data
> [tbc-ge] Fix sum is NaN in Utils

- src/plugins/etherscan/tokens/config.ts
change USDT to match actual instrument
change USDC/BUSD to match Troncoin
> etherscan: change instrument for stablecoins to USDT

- src/plugins/timo-vn/ZenmoneyManifest.xml
- src/plugins/timo-vn/__tests__/converters/accounts/account.test.ts
- src/plugins/timo-vn/__tests__/converters/accounts/card.test.ts
- src/plugins/timo-vn/__tests__/converters/transactions/outcome.test.ts
- src/plugins/timo-vn/api.ts
- src/plugins/timo-vn/converters.ts
- src/plugins/timo-vn/fetchApi.ts
- src/plugins/timo-vn/index.ts
- src/plugins/timo-vn/models.ts
- src/plugins/timo-vn/preferences.xml
Support for [timo.vn](https://timo.vn/)
What is working:
Auth and trusting device with OTP
Debit cards
Transactions
Cash withdrawal
What is NOT working:
Deposits
Loans
Split accounts
> [timo-vn] Initial support for timo.vn

- src/plugins/apelsin-uz/api.js
- src/plugins/apelsin-uz/auth.js
Пофикшена проблема с требованием обновить версию приложения #778.
> [apelsin-uz] Fix auth flow for Apelsin/Uzum bank #778

- src/plugins/timo-vn/__tests__/converters/accounts/account.test.ts
- src/plugins/timo-vn/__tests__/converters/accounts/card.test.ts
- src/plugins/timo-vn/__tests__/converters/transactions/outcome.test.ts
- src/plugins/timo-vn/converters.ts
Fix issue with missed remainAmount #781 
Tests updated
> [timo-vn] Fix issue with missed remainAmount

- src/plugins/vakifbank-tr/__tests__/statementTransaction.test.ts
- src/plugins/vakifbank-tr/api.ts
- src/plugins/vakifbank-tr/converters.ts
There were 2 problems
1. Account currency didn't parse. Fixed now.
2. If an imported file has multiple movements to other accounts, it collects all of them into a first row. Fixed now.
Also refactored a little, to make things easier.
if you approve, let me know please when it comes to iPhones.
> [vakifbank-tr] Fix bugs with pdf parser

- src/plugins/yettelbank-rs/__tests__/parsers/transactions.html
- src/plugins/yettelbank-rs/__tests__/parsers/transactions.test.ts
- src/plugins/yettelbank-rs/fetchApi.ts
quick fix в догонку к утреннему пр, немного напортачила с транзакциями 😄
исправила парсер транзакций, поправила тесты и добавила +1 тест кейс
> [yettelbank-rs] fixed transactions parser to process incoming and outgoing transactions

- src/plugins/timo-vn/api.ts
- src/plugins/timo-vn/index.ts
- src/plugins/timo-vn/models.ts
Updated app version
App version error handled
> [timo-vn] Update app version

- src/plugins/bankofgeorgia-business-ge/converters.ts
Fix issue with assertion for private transfers
change DocumentProductGroup to the latest api version
> [bankofgeorgia-business-ge] fix: change payment types according latest docs

- src/plugins/bankofgeorgia-business-ge/__tests__/converters/transactions/transaction.test.ts
- src/plugins/bankofgeorgia-business-ge/converters.ts
Adjust logic for same data transfers and make tests pass
> [bankofgeorgia-business-ge] fix: adjust logic for foreign currency

- src/plugins/timo-vn/api.ts
- src/plugins/timo-vn/index.ts
- src/plugins/timo-vn/models.ts
-Updated app version
-Simple refactoring for define app version in 1 place
> [timo-vn] App version updated

- src/plugins/bankofgeorgia-ge/__tests__/converters/getAmountFromDescription.test.ts
- src/plugins/bankofgeorgia-ge/__tests__/converters/transactions/cashTransfer.test.ts
- src/plugins/bankofgeorgia-ge/__tests__/converters/transactions/purchase.test.ts
- src/plugins/bankofgeorgia-ge/converters.ts
> bankofgeorgia-ge: invoice field fix

- src/plugins/bnbank/api.js
Based on: https://bnb.by/chtoby-znali/novosti/obnovlyaemsya-dobavili-novye-vozmozhnosti-prilozheniya-bnb-bank-i-vernuli-davno-ozhidaemye/
It's possible now to sync Bnb Bank without losing access to the application (from the end of Mar 2024, the possibility was lost because of 1 app - 1 user relationship limit). So the flow is the following:
To add a second device, you need:
1. Regular login from ZenMoney
2. You'll receive the error to confirm the login from the trusted app
3. After clicking Confirm in the bank app from the phone, you'll receive the SMS with the code that should be inserted into the login request
Confirmations:
1. First sync
2. Second and the following sync (no need to enter SMS):
> [bnbank] restore the possibility to sync BNB bank

- src/plugins/otpbank-rs/api.ts
- src/plugins/otpbank-rs/preferences.xml
Fix the broken sync with OTP Bank RS
> [otpbank-rs] Ask for mBank token for each login

- src/plugins/timo-vn/index.ts
> [timo-vn] Client version update

- src/plugins/yettelbank-rs/ZenmoneyManifest.xml
- src/plugins/yettelbank-rs/api.ts
- src/plugins/yettelbank-rs/fetchApi.ts
- src/plugins/yettelbank-rs/preferences.xml
* Added fetching transactions with date filter
* Updated login to not reuse auth object
> [yettelbank-rs] Added date filtering, updated login

- src/plugins/bankofgeorgia-ge/__tests__/converters/transactions/cashTransfer.test.ts
- src/plugins/bankofgeorgia-ge/__tests__/converters/transactions/other.test.ts
- src/plugins/bankofgeorgia-ge/__tests__/converters/transactions/transfer.test.ts
- src/plugins/bankofgeorgia-ge/converters.ts
> [bankofgeorgia-ge] fix cash withdrawal comission transactions in foreign currency and cash withdrawal comments and merchant

- src/plugins/otpbank-rs/__tests__/converters/transactions.ts
- src/plugins/otpbank-rs/converters.ts
- src/plugins/otpbank-rs/models.ts
- src/plugins/otpbank-rs/parsers.ts
Decode HTML entities in the transaction title like &amp; → &
> [otpbank-rs] Decode HTML entities in the transaction title, proper transaction parsing

- src/plugins/solana/converters.ts
> [solana] use fee as diff if diff is zero

- src/plugins/yettelbank-rs/ZenmoneyManifest.xml
- src/plugins/yettelbank-rs/fetchApi.ts
Bugfix when there are no transactions or there are no pages - the plugin continue works.
> [yettelbank-rs] Bugfix when there are no transactions or there are no pages

- src/plugins/kaspi/api.ts
Deposit transaction list was updated (was added some whitespaces).
I fixed regex and header string search.
> [kaspi] parsing deposit transactions fix

- src/polyfills/webAssembly.js
> [raiffeisen-rs] Always use polywasm

- src/plugins/kredobank-ua/api.js
This fix avoid fetching inactive accounts and cards. If the inactive account is requested, the 400 error will be returned. 
Error response body:  
```
{
errorMessageKey: 'access_forbidden',
errorDescription: 'Not allowed to view history for contract 13856132'
}
```
> [kredobank-ua] Avoid fetching inactive accounts

- src/plugins/bnbank/api.js
Before:
Ref:
Confirmation, that everything works fine after that change:
> [bnbank] bump app version

- src/plugins/credo-ge/api.ts
> fix(credo-ge): Fixing changed login workflow

- src/plugins/etherscan/common/index.ts
- src/plugins/etherscan/mocks/index.ts
> [etherscan] Migrate to API v2

- src/plugins/altabanka-rs/index.ts
- src/plugins/altabanka-rs/transactions.ts
Тransactions have started to duplicate recently.
>  [altabanka-rs] Adding "deduplicateTransactions" function

- src/plugins/timo-vn/index.ts
> [timo-vn] Updated web client's version
