plugins/belswissbank/main.js

motivated by @skvav 
replace synthetic `id` for merged transfer transactions with separate `incomeBankID` and `outcomeBankID`
sample transfer transaction diff 
```diff
-      "id": "12377125+12377126",
+      "incomeBankID": "12377126",
+      "outcomeBankID": "12377125",
```

[belswissbank] provide incomeBankID and outcomeBankID instead of combined id for transfer transactions

---

plugins/epayments/ZenmoneyManifest.xml
plugins/epayments/classes/BankEpayments.js

http://support.zenmoney.ru/topics/322-oshibka-epayments-exception-typeerror-null-is-not-an-object-evaluating-dataitemprevcardidsubstr/

[epayments] fixes for prepare cards data

---

scripts/start.js
src/plugins/bootloader/ZenmoneyManifest.xml
src/plugins/bootloader/index.js
src/plugins/bootloader/preferences.xml

adds ability to load plugin straight from developer host
use
PRODUCTION=true PORT=%port-to-bind% HOST=%host-to-bind% to start building plugin as a standalone package
plugin will be compiled and available on %host-to-bind%:%port-to-bind%/index.js

[bootloader] implementation

---

src/common/adapters.js
src/common/adapters.test.js
src/common/dates.js

seems like transactions added by UI internally have 00:00:00 time set
transactions from bank with provided time are now always sorted as "newer" than all newer manually added ones in UI
now we're automatically cropping time to make bank transactions order the same way as manually added in list
note: when feature `dateProcessing` will be implemented, transactions added by UI must have valid time set to ensure correct ordering inside day

fix dates interpretation issue: manually added transactions are all before imported from bank

---

src/common/mergeTransfers.js
src/plugins/alfabank/preferences.js

(Object.entries is not polyfilled)

[alfabank] replace Object.entries usages with _.toPairs

---

src/common/accounts.js
src/common/accounts.test.js
src/common/adapters.js
src/plugins/alfabank/__snapshots__/converters.test.js.snap
src/plugins/alfabank/api.js
src/plugins/alfabank/converters.js
src/plugins/alfabank/converters.test.js
src/plugins/alfabank/index.js
src/plugins/alfabank/preferences.js
src/plugins/alfabank/preferences.test.js
src/plugins/alfabank/preferences.xml

[alfabank] stabilization

---

src/plugins/alfabank/converters.js

fixes `Assertion failed: one side must be sender (outcome)` reported by 546606

[alfabank] ignore non-transfer operation transaction type

---

src/plugins/bgpb/__tests__/converters/accounts.test.js
src/plugins/bgpb/api.js
src/plugins/bgpb/converters.js
src/plugins/bgpb/index.js

ProductId каждую новую сессию меняет свою правую часть, отделенную дефисом, в то время как реализация функциональности skip account рассчитывает на постоянство этого id.
Как результат, до фикса аккаунты не скипались и дублировались в списке:
+ уменьшается количество запросов (теперь не делаем таковые для скипнутых аккаунтов)

[bgpb] make account.id stable; implement isAccountSkipped filtering

---

src/common/converters.js
src/plugins/bgpb/converters.js

`[ZP] Exception: __ [TMC] Invalid transaction 2019-05-06 1:25:00 pm +0000. merchant.mcc must be null or integer number > 0`
assert на mcc со стороны iOS app строже чем используемые в разработке

[bgpb] handle invalid 0 mcc, sync asserts with native app

---

src/plugins/alfabank-by/__tests__/converters/accounts.test.js
src/plugins/alfabank-by/__tests__/index.test.js
src/plugins/alfabank-by/api.js
src/plugins/alfabank-by/converters.js
src/plugins/alfabank-by/index.js

До этого ПР карточки по сути не синхронизировались в плагине, а только их счета, из-за чего новые операции приходили как корректировки.
Данное обновление может вызвать окно создания/присоединение картсчета во время первой синхронизации. Это нормально, т.к. используются дополнительные id карточки.

[alfabank-by] Card processing

---

src/plugins/bnbank/api.js
src/plugins/bnbank/index.js

- Исправлена загрузка последних операций по карточкам
- Исправлена ситуация, когда работали только те аккаунты, где были депозиты. Вообще я удивлен что никто ни разу не пожаловался что синхронизация для "обычных" аккаунтов вообще не работала столько месяцев

[bnbank] Fix last transaction fetching

---

src/plugins/kapitalbank-uz/api.js
src/plugins/kapitalbank-uz/converters.js

Исправил:
- Ошибку корректировки в нулевой баланс во время downtime'ов на стороне процессингового центра. Такие карты будут пропускаться.
- Ошибку при загрузке карт, выпущенных другим банком, но добавленных в интернет-банкинг. У них отсутствует информация о номере картсчета, поэтому один из `syncID` сохранялся как `java.lang.Object@c54bbae`. Теперь проверяется наличие номера картсчета и сохраняется в `syncID` если имеется.
- Ошибку при загрузке истории карт, где сумма транзакции имеет два и более пробела-разделителя. Например, `1 000 000`. Теперь удаляются все пробелы-разделители.
- Ошибку при загрузке истории карт VISA, при снятии определенной суммы и моментальном возврате таким образом, что сумма транзакции из банка возвращается `0.00`. Такие транзакции будут пропускаться.
\+ немного …

[kapitalbank-uz] Bugfixes, refactor and improvements

---

src/plugins/bgpb/converters.js

Исправлена ошибка возникающая в процессе обработки транзакций
Ошибка возникала по причине того, что транзакция  'Смена PIN' имеет формат отличный от стандартной транзакции

Bgpb handle change pin transaction

---

src/plugins/ineco/converters.js
src/plugins/ineco/session.js

локально все работает корректно, но на мобильном - нет
по логам видно что все запросы проходят и возвращают данные, но, судя по логам, на мобильном данные приходят юникодными символами (/u0000) из-за чего парсер не работает
добавил кодировку в заголовки и дополнительно залогировал часть ответа, чтоб было понятно если проблема сохранится

[ineco] set charset and check some debug info

---

src/plugins/kapitalbank-uz/converters.js

При получении операций, где сумма комиссии превышает сумму расхода, вылетает exception. Решили с @skvav, что самым простым решением будет включение комиссии в сумму расхода.

[kapitalbank-uz] Get Visa transactions bugfix

---

src/plugins/bnbank/converters.js
src/plugins/dabrabyt/index.js

Desc of fixes:
1. There is no field OperationType - only OperationCode
2. Changed >= to >, because all operations are becoming cash operations (not all, only if they do not have OperationName - for new(less than 2 days - it is all operations).
3. Add new templating to show that it is the net-bank operation
@skvav believe that it would be mostly all with BNB :)

Fix: BNB most transactions take away from cash

---

src/plugins/bnbank/__tests__/converters/transactions/transaction.test.js
src/plugins/bnbank/__tests__/converters/transactions/transfer.test.js
src/plugins/bnbank/__tests__/index.test.js
src/plugins/bnbank/converters.js

It's the wrong amount in a case when the currency of payment differs from the account currency.
Before fix:
transaction api response:
transaction info in list:
After fix:
Also was added a useful comment with the initial payment amount and currency

[bnbank] fix transaction currency and amount

---

src/plugins/forwardbank/api.js

Убрал использование UrlSearchParams т.к его нет в es5  и добавил санитайзинг лога

[forwardbank] fix UrlSearchParams is not defined 

---

src/plugins/belswissbank/BSB.js
src/plugins/belswissbank/__tests__/BSB.test.js
src/plugins/belswissbank/converters.js

But fall back to `sum: null` feature instead of dropping transactions having smsTx.accountRest=null. And statement is joined as well, that should eventually give close to zero balance corrections.

[belswissbank] revert: now sum=figureOutAccountRestsDelta (gives less corrections)

---

src/plugins/eubank/converters.js

Сейчас в текущем балансе счета не учитывается заблокированная сумма и на странице "Операции" все время показывает что не хватает поступлений. Этот фикс исправит эту ошибку.

[eubank] Fix for current balance of account

---

src/plugins/tronscan/api.ts

Судя по всему в API Tronscan какой-то баг, из-за которого приходит меньше операций, чем должно быть. Поменял условия выхода из цикла, чтобы в таком случае интеграция не падала

fix tronscan while condition

---

src/plugins/vakifbank-tr/converters.ts

В вакифбанке при переводе создаётся доп. транзакция на комиссию, сумма из которой записывается в дзенмани не отдельной транзакцией, а в поле `fee`. Это значение должно быть положительным.

[vakifbank-tr] Fix incorrect fee

---

src/plugins/raiffeisen-business-rs/ZenmoneyManifest.xml
src/plugins/raiffeisen-business-rs/__tests__/converters/accounts/account.test.ts
src/plugins/raiffeisen-business-rs/__tests__/converters/transactions/income.test.ts
src/plugins/raiffeisen-business-rs/__tests__/converters/transactions/payment.test.ts
src/plugins/raiffeisen-business-rs/__tests__/converters/transactions/transfer.test.ts
src/plugins/raiffeisen-business-rs/converters.ts
src/plugins/raiffeisen-business-rs/fetchApi.ts
src/plugins/raiffeisen-business-rs/index.ts
src/plugins/raiffeisen-business-rs/models.ts
src/plugins/raiffeisen-business-rs/preferences.xml

Поддержка бизнес версии Raiffeisen Bank Serbia
Основано на raiffeisen-rs, апишка похожа, но со своими особенностями
Переводы со счета на счет реализованы для операций продажи валют USD/EUR -> RSD, в обратную сторону нет возможности протестировать.

[raiffeisen-business-rs] Add initial support for Raiffeisen Bank Serbia Business

---

src/plugins/tonscan/ZenmoneyManifest.xml
src/plugins/tonscan/__tests__/converters/accounts/accounts.test.ts
src/plugins/tonscan/__tests__/converters/transaction/transaction.test.ts
src/plugins/tonscan/__tests__/tonscan-scrape.test.ts
src/plugins/tonscan/api.ts
src/plugins/tonscan/config.ts
src/plugins/tonscan/converters.ts
src/plugins/tonscan/index.ts
src/plugins/tonscan/mocks/index.ts
src/plugins/tonscan/preferences.xml

Added plugin for synchronisation with [tonscan.org](https://tonscan.org/)
For now it supports TON and USDT wallets, but its possible to add support for other tokens(aka jettons).  
It uses [toncenter v3 api](https://toncenter.com/api/v3) which does not require an api key, but limits you with 1 request per second. In this first version I haven't added support for using users's api key and instead added 1.3s delay between requests, so sync can take from 5-7s to tens of seconds depending on number of your transactions. For example it will take ~25s to sync 3 wallets with usdt jetton in each with in total 72 transactions.  
Later I can add support for custom api key to speed up sync.
- Ton account name is its user-friendly address, for example …

[tonscan] Add tonscan plugin

---

src/plugins/raiffeisen-business-rs/converters.ts
src/plugins/raiffeisen-business-rs/models.ts

For transactions on foreign currency accounts, the DebtorCreditorName may sometimes be null, causing the convertTransaction function to fail. To address this, the fix implements a fallback mechanism that uses Trnben or defaults to 'Unknown' in these scenarios.

[raiffeisen-business-rs] Fix handling of transactions with no DebtorCreditorName

---

src/plugins/bankofgeorgia-business-ge/ZenmoneyManifest.xml
src/plugins/bankofgeorgia-business-ge/__tests__/converters/accounts/account.test.ts
src/plugins/bankofgeorgia-business-ge/__tests__/converters/transactions/transaction.test.ts
src/plugins/bankofgeorgia-business-ge/api.ts
src/plugins/bankofgeorgia-business-ge/converters.ts
src/plugins/bankofgeorgia-business-ge/fetchApi.ts
src/plugins/bankofgeorgia-business-ge/index.ts
src/plugins/bankofgeorgia-business-ge/models.ts
src/plugins/bankofgeorgia-business-ge/preferences.xml

Following up on #756.
During the development, I discovered there's an official API for BoG Business customers.
Hopefully, with these changes transactions from BoG Business will be automatically linked with individual BoG transactions.
- Auth with Client ID and Client Secret from official API
- Transaction syncing with the following types:
- Card payments (with MCC parsing)
- Outgoing transfers
- Incoming transfers
- Currency exchanges
- Automatic conversions
- Fees
- Balance fetching for accounts
The plugin has been tested with data from my BoG Business account.
There are also some test cases with mock data, although they don't cover all cases and plugin functionality.

Add initial support for Bank of Georgia Business

---

src/plugins/bankofgeorgia-business-ge/converters.ts

Following up #765 after testing in mobile app. 
Initial sync fails with the following exception:
`[ZP] Exception: _ [TMT] Invalid transaction xxxxxxxxxx. merchant.title must be non-empty string`
This should fix it.

[bankofgeorgia-business-ge] Handle cases when BeneficiaryDetails.Name is empty string

---

src/ZPAPI.js
src/plugins/tbc-ge/converters.ts

Sync failed because of of loan percent being null. Unfortunately changes from #759 was a little misleading. It looked like now ZPAPI.js allows it to be null, but it's not. It is safe to use just default 0 value in converter.

[tbc-ge] Loan percent should always be numeric value, add default

---

src/plugins/tbc-ge/__tests__/convertersV2/transactions/currencyExchange.test.ts
src/plugins/tbc-ge/__tests__/convertersV2/transactions/currencyExchangeAdjust.test.ts
src/plugins/tbc-ge/common-tests/accountsV2.ts
src/plugins/tbc-ge/converters.ts

This introduces groupKeys usage in transfers, so transactions with the same `transactionId` and `title` are considered a part of one operation.
Closes #773

[tbc-ge] currency auto-conversion counts as an income

---

.github/workflows/test.yml
package.json
scripts/checkCommit.js

Add tests in Github Actions
Add commit name checks

[core] Github Actions tests

---

src/plugins/tronscan/api.ts
src/plugins/tronscan/config.ts
src/plugins/tronscan/converters.ts
src/plugins/tronscan/index.ts

Changes include 2 things:
– Changed field for TRX balance. `amount` also includes staked TRX in the balance. I think this is better behavior
– There can be unknown transactions. For example, operations with smart contracts outside of the supported scope. Those operations can have «fee» in TRX and it will change TRX balance. Right now, these operations simply ignored

Tron improvements

---

src/plugins/solana/api.ts
src/plugins/solana/converters.ts
src/plugins/solana/types.ts

currently plugin fails if it stumbles on some transactions because API doesn't return fields plugin expects for them, since they're not legacy txns
use jsonParsed encoding with maxSupportedTransactionVersion:0 when calling getTransaction, and update other logic accordingly.
also fix the fee calculation to make it more robust and generic.

solana: update for non-legacy transactions

---

src/plugins/yettelbank-rs/__tests__/parsers/accounts.test.ts
src/plugins/yettelbank-rs/__tests__/parsers/transactions-empty.html
src/plugins/yettelbank-rs/__tests__/parsers/transactions.test.ts
src/plugins/yettelbank-rs/api.ts
src/plugins/yettelbank-rs/fetchApi.ts
src/plugins/yettelbank-rs/index.ts

In Yettel, one account can have several currencies, which looks and operated like several sub-accounts.
In this PR, I'm parsing these sub-accounts and separating transactions by currency-sub-acc.
Covered with tests.

[yettelbank-rs] Separate accounts by currency sub-account

---

src/plugins/raiffeisen-rs/converters.ts

Зачем: сломан парсинг снятия наличных в валюте отличающейся от валюты счета
`Invalid transaction opIncome and opOutcome must have same sign as income and outcome`
<details><summary>пример ломающей транзакции</summary>
замазал все чувствительное
```json
// ответ от райфа
[
{
"e_UserLocality": null,
"ReceiveDate": null,
"fwType": "aoFullTransactionDetails",
"m_PayDeskNumber": null,
"CurrencyCodeNumeric": null,
"p2p_Message": null,
"p2p_Status": null,
"s_Alias": null,
"m_UserGroup": null,
"Alias": null,
"dev_cred_bank_address_postal": null,
"e_UserName": null,
"c_Alias": null,
"m_ExchangeOfficeLocality": null,
"dev_Status": null,
"DebtorName": null,
"c_TerminalID": "********",
"m_Basics": null,
"p2p_CurrencyCodeNumeric": null,
"ValueDate": null,
"s_Note_st": "MATBUOTCHILAR 9 UZB TOSHKENT", …
```

[raiffeisen-rs] remove invoice from cash income movement

---

src/plugins/bscscan/ZenmoneyManifest.xml
src/plugins/bscscan/__tests__/converters/accounts/accounts.test.ts
src/plugins/bscscan/__tests__/converters/bnb-scrape.test.ts
src/plugins/bscscan/__tests__/converters/transaction/transaction.test.ts
src/plugins/bscscan/bnb/api.ts
src/plugins/bscscan/bnb/converters.ts
src/plugins/bscscan/bnb/index.ts
src/plugins/bscscan/bnb/types.ts
src/plugins/bscscan/common/converters.ts
src/plugins/bscscan/common/index.ts
src/plugins/bscscan/common/types.ts
src/plugins/bscscan/index.ts
src/plugins/bscscan/mocks/index.ts
src/plugins/bscscan/preferences.xml
src/plugins/bscscan/tokens/bep20.ts
src/plugins/bscscan/tokens/config.ts
src/plugins/bscscan/tokens/converters.ts
src/plugins/bscscan/tokens/index.ts
src/plugins/bscscan/tokens/types.ts
src/plugins/bscscan/types.ts

This plugin based on `etherscan` plugin because API interfaces of bscscan and etherscan are similar.

[bscscan] Add bscscan plugin for BNB and BEP20 tokens support

---

src/plugins/bnbank/__tests__/index.test.js
src/plugins/bnbank/api.js
src/plugins/bnbank/converters.js

AR:
Since around mid 2024, when BNB Bank changed their API, it has become impossible to retrieve unconfirmed transactions — the `getBlockedAmountStatement` request always returns 0 transactions.
ER:
There is another request, `getCardTransactions`, which resolves this issue.
NOTE:
The current implementation is not complete — it could potentially be improved by filtering only transactions with the “processing” status and verifying that all fields are parsed correctly (as the structure differs slightly).
However, since the API is closed, debugging the app would take significantly more time. Zenmoney already merges transactions correctly, so there’s no urgent need for further adjustments. The structure is consistent for all main fields, so in case a bug arises, fixing it should be …

[bnbank] Improve(fix) last transactions (add processing ones)

---

src/plugins/altabanka-rs/converters.ts
src/plugins/altabanka-rs/index.ts

On July 1st, for some reason, the bank issued zero transactions to everyone. Which were not processed by the plugin. Because of this, the synchronization broke down.

[altabanka-rs] Adding zero transaction processing

---

src/plugins/bankofgeorgia-business-ge/index.ts

For bankofgeorgia-business-ge plugin I add adjust transactions, because after receiving in applications no new transactions were saved. I have only updated sum on my account, but if I reopen the application my sum will be updated for old values and no new transactions will be saved.

[bankofgeorgia-business-ge] add adjust transactions
